CREATE TABLE IF NOT EXISTS WWI.DimDate (
    DateKey INT NOT NULL,
    Date Date NOT NULL,
    Year INT NOT NULL,
    Month INT NOT NULL,
    Day INT NOT NULL,
    Quarter INT NOT NULL,
    DayOfWeek INT NOT NULL,
    DayOfYear INT NOT NULL,
    WeekOfYear INT NOT NULL
)
COMMENT 'Date Information'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';
